name: Design Discussion
description: Propose or discuss changes to Lingua Sona’s design
labels: ["design"]
body:
  - type: textarea
    attributes:
      label: Proposal or Question
      description: Describe the design idea or concern clearly.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Rationale
      description: Explain why this matters and what problem it solves.

